name: Rust Stable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Check all features
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all-features
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
